import Head from 'next/head'
import DefaultHeader from '../layout/Default'


export default function Home() {
  return (
    <div>
      <Head>
        <title>College</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <DefaultHeader>

          </DefaultHeader>
    </div>
  )
}
